evm_substate_height = 0
disable_evm_block_height = 0
enable_frc20_height = 0
evm_first_block_height = 0
zero_amount_fix_height = 0
apy_fix_height = 0
overflow_fix_height = 0
second_fix_height = 0
apy_v7_upgrade_height = 0
ff_addr_extra_fix_height = 0
nonconfidential_balance_fix_height = 0
unbond_block_cnt = 113400
prismxx_inital_height = 1
enable_triple_masking_height = 0
fix_unpaid_delegation_height = 0
evm_checktx_nonce = 0
utxo_checktx_height = 0
utxo_asset_prefix_height = 0
prism_bridge_address = ""
nonce_bug_fix_height = 0
