[package]
name = "fp-utils"
version = "0.1.0"
authors = ["FindoraNetwork"]
edition = "2021"
homepage = "https://findora.org/technology"
repository = "https://github.com/findoranetwork/platform/"
description = "Findora Primitive utility functions"
readme = "README.md"

[dependencies]
futures = "0.3.16"
base64 = "0.12"
bip0039 = "0.8.0"
blake2-rfc = "0.2.18"
byteorder = "1.4.3"
hex = "0.4.2"
libsecp256k1 = { version = "0.5", features = ["static-context", "hmac"] }
primitive-types = { version = "0.11.1", default-features = false, features = ["rlp", "byteorder", "serde"] }
protobuf = "2.16"
rand = "0.8"
ruc = "1.0"
serde = { version = "1.0.124", features = ["derive"] }
sha2 = "0.9.5"
sha3 = "0.8"
bip32 = "0.4.0"
tiny-keccak = { version = "2.0", features = ["keccak"] }
twox-hash = "1.6.0"

[dev-dependencies]
hex-literal = "0.3.1"
serde_json = "1.0"
