[package]
name = "wallet"
version = "0.1.0"
authors = [ "FindoraNetwork" ]
edition = "2018"

[dependencies]
ruc = { git = "https://github.com/FindoraNetwork/RUC.git", branch = "master" }
rand = "0.8"
bip0039 = "0.7.3"

ed25519-dalek-bip32 = { git = "https://github.com/FindoraNetwork/ed25519-dalek-bip32", branch = "feat-allow-nohardened" }
zei = { git = "ssh://git@github.com/FindoraNetwork/zei", tag = "v0.1.4" }

bech32 = "0.7.2"
base64 = "0.10"

[dev-dependencies]
rand_chacha = "0.2"
rand_core = "0.5"
