[package]
name = "txn_builder"
version = "0.1.0"
authors = ["Nathan Yospe <nathan@eian.io>"]
edition = "2018"

[lib]
path = "src/txn_builder.rs"

[dependencies]
ruc = { git = "https://github.com/FindoraNetwork/RUC.git", branch = "master" }
ledger = { path = "../../ledger" }
credentials = { path = "../../libs/credentials" }
sparse_merkle_tree = { path = "../../libs/ads/sparse_merkle_tree" }
utils = { path = "../../libs/utils" }
curve25519-dalek = { version =  "3", features = ["serde"] }
serde = "1.0.124"
serde_derive = "1.0"
serde_json = "1.0"
rand_core = { version = "0.5", default-features = false, features = ["alloc"] }
rand_chacha = "0.2.0"
wasm-bindgen = { version = "0.2.50", features = ["serde-serialize"]  }
zei = { git = "ssh://git@github.com/FindoraNetwork/zei", tag = "v0.1.4" }
tendermint = "0.19.0"

[dev-dependencies]
quickcheck = "0.8"
quickcheck_macros = "0.8"
