[package]
name = "submission_server"
version = "0.1.0"
authors = ["Nathan Yospe <nathan@eian.io>"]
edition = "2018"

[lib]
path = "src/submission_server.rs"

[dependencies]
actix-web = "1.0"
hex = "0.3.2"
cryptohash = { path = "../../libs/cryptohash" }
ledger = { path = "../../ledger" }
log = "0.4.8"
rand_chacha = "0.2.0"
rand_core = { version = "0.5", default-features = false, features = ["alloc"] }
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
txn_builder = {path = "../txn_builder"}
zei = { git = "ssh://git@github.com/findoraorg/zei", tag = "v0.0.1" }
