[package]
name = "query_api"
version = "0.1.0"
authors = ["Noah Golub <noah@findora.org>"]
edition = "2018"
build = "build.rs"

[lib]
name = "query_api"
path = "src/query_api.rs"

[[bin]]
name = "query_server"
path = "src/query_server_launch.rs"

[dependencies]
ruc = { git = "https://github.com/FindoraNetwork/RUC.git", branch = "master" }
actix-cors = "0.5.4"
actix-rt = "1.1.0"
actix-service = "1.0.6"
actix-web = "3.3.2"
parking_lot = "0.11.1"
ledger = { path = "../../ledger" }
futures = "0.3"
ledger_api_service = { path = "../ledger_api_service"}
log = "0.4.8"
metrics = "0.13.1"
metrics-exporter-prometheus = "0.2.0"
query_server = {path = "../query_server"}
rand_core = { version = "0.5", default-features = false, features = ["alloc"] }
rand_chacha = "0.2.0"
serde = "1.0.124"
serde_derive = "1.0"
serde_json = "1.0"
sparse_merkle_tree = { path = "../../libs/ads/sparse_merkle_tree" }
utils = { path = "../../libs/utils" }
zei = { git = "ssh://git@github.com/FindoraNetwork/zei", tag = "v0.1.0d" }

[build-dependencies]
vergen = "3.1.0"
