[package]
name = "fp-rpc-server"
version = "0.1.0"
authors = ["FindoraNetwork"]
edition = "2021"
homepage = "https://findora.org/technology"
repository = "https://github.com/findoranetwork/platform/"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
description = "EVM RPC servers."
readme = "README.md"

[dependencies]
futures = "0.3.16"
jsonrpc-core = "18.0.0"
pubsub = { package = "jsonrpc-pubsub", version = "18.0.0" }
log = "0.4.8"
serde_json = "1.0.41"

http = { package = "jsonrpc-http-server", version = "18.0.0" }
ipc = { package = "jsonrpc-ipc-server", version = "18.0.0" }
ws = { package = "jsonrpc-ws-server", version = "18.0.0" }
